# Generated by Django 4.2.3 on 2023-08-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
