# Generated by Django 4.2.3 on 2023-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
