# Generated by Django 4.2.3 on 2023-08-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='notes',
            field=models.CharField(max_length=255),
        ),
    ]
