# Generated by Django 4.2.3 on 2023-08-06 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_patient_summary'),
        ('doctor', '0003_alter_slot_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_booking', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancel', 'Cancelled')], default='pending', max_length=10)),
                ('payment_type', models.CharField(choices=[('online', 'Online Payment'), ('wallet', 'Wallet')], default='wallet', max_length=10)),
                ('token', models.CharField(editable=False, max_length=6, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.slot')),
            ],
        ),
    ]
