# Generated by Django 4.2.3 on 2023-08-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_doctor_image_alter_doctor_is_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('doctor', 'date', 'time')},
        ),
    ]
